In [9]:
import numpy as np
import random
import pandas as pd

In [5]:
# To generate 25 random numbers between 1-100 to use as index for selecting the youtube channel data.
# Doing the same process for top 100 lists of 5 different countries.
random_index_us = random.sample(range(1, 101), 25) #using random function to generate 25 numbers in 1 to 100 range.
print('Index for US: ',random_index_us)

random_index_uk = random.sample(range(1, 101), 25)
print('Index for UK: ',random_index_uk)

random_index_aus = random.sample(range(1, 101), 25)
print('Index for AUSTRALIA: ',random_index_aus)

random_index_can = random.sample(range(1, 101), 25)
print('Index for CANADA: ',random_index_can)

random_index_ger = random.sample(range(1, 101), 25)
print('Index for GERMANY: ',random_index_ger)

Index for US:  [68, 99, 1, 63, 97, 71, 98, 39, 36, 14, 100, 52, 11, 4, 13, 96, 80, 62, 45, 65, 86, 89, 40, 17, 95]
Index for UK:  [65, 83, 90, 84, 89, 9, 47, 98, 53, 8, 39, 87, 94, 16, 61, 5, 55, 93, 36, 85, 4, 59, 27, 66, 79]
Index for AUSTRALIA:  [33, 77, 23, 97, 15, 45, 58, 79, 88, 50, 24, 83, 59, 42, 21, 84, 62, 27, 19, 37, 32, 6, 26, 78, 98]
Index for CANADA:  [68, 93, 42, 10, 13, 78, 96, 54, 30, 1, 47, 24, 50, 45, 7, 52, 70, 75, 66, 11, 64, 31, 12, 100, 29]
Index for GERMANY:  [65, 14, 42, 52, 84, 73, 15, 77, 100, 60, 86, 30, 87, 17, 9, 3, 97, 24, 71, 82, 51, 11, 83, 10, 79]


In [10]:
ds1 = pd.read_excel('Dataset 1_YT_subcount.xlsx') #calling excel data into jupyter notebook using pandas library.
display(ds1.head())
ds1['sub_count'] = ds1['sub_count'].astype('int') # convert sub_count column values from string to integer
ds1.shape

channel_name   sub_count  \
0          Wildlife Shorts    723000.0   
1                Jojo Sim   10800000.0   
2        TheSoul Music FUN   3530000.0   
3  Meaningful Cartoons 183   1340000.0   
4            The McCartys    8650000.0   

                                          link  
0     https://www.youtube.com/@wildlife.shorts  
1             https://www.youtube.com/@jojosim  
2    https://www.youtube.com/@thesoulmusic-fun  
3  https://www.youtube.com/@meaningfulcartoons  
4       https://www.youtube.com/@themccartyfam

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [17]:
ds1.describe()
pd.unique(ds1['sub_count'])

array([7.2300000e+05, 1.0800000e+07, 3.5300000e+06, 1.3400000e+06,
       8.6500000e+06, 1.0500000e+07, 6.9500000e+07, 1.3400000e+07,
       2.8000000e+06, 1.5300000e+07, 6.4300000e+06, 8.2200000e+06,
       1.3700000e+07, 4.2800000e+07, 5.8800000e+06, 3.1300000e+07,
       2.1700000e+07, 5.6200000e+06, 6.5400000e+06, 1.9500000e+07,
       2.4800000e+07, 5.1600000e+06, 8.4700000e+06, 6.4500000e+06,
       3.8500000e+05, 9.7200000e+05, 3.0400000e+07, 1.7200000e+07,
       1.3700000e+05, 3.7400000e+06, 3.4200000e+06, 9.8600000e+06,
       5.9700000e+06, 2.2700000e+06, 3.2100000e+07, 5.7400000e+06,
       2.5400000e+07, 6.7100000e+06, 7.9700000e+05, 7.4100000e+05,
       1.0700000e+06, 9.4000000e+06, 4.9600000e+05, 8.0000000e+05,
       3.9300000e+06, 1.6400000e+07, 2.7100000e+06, 2.5500000e+06,
       6.7700000e+06, 4.8100000e+05, 5.6800000e+05, 7.2800000e+06,
       3.8900000e+05, 6.2500000e+06, 5.1600000e+05, 7.6700000e+05,
       1.0800000e+06, 9.8600000e+05, 1.4800000e+07, 4.0400000e

In [8]:
np.histogram(ds1['sub_count'],bins=11) #To figure out class interval for frequency table

ValueError: autodetected range of [nan, nan] is not finite

## Dataset 2- clock times of 110 consecutive car crossings

In [48]:
ds2=pd.read_excel('Dataset 2_clocktime_cars.xlsx')

In [28]:
ds2.columns


Index(['Clock time', 'Interval between occurrences', 'Interval (in seconds)',
       'Unnamed: 3', 'Unnamed: 4'],
      dtype='object')

In [49]:
ds2= ds2.fillna(0)


In [50]:
np.histogram(ds2['Interval (in seconds)'],bins=10)

(array([28, 37, 15,  5,  7,  5,  4,  4,  2,  3], dtype=int64),
 array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]))